version: 2

models:
  - name: fact_transaction
    columns:
      - name: codigo_transacao
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: estado_transacao
        description: "Check if values match accepted values described in the prbolem"
        tests:
          - accepted_values:
              values: ['PAID', 'REFUSED', 'REFUNDED', 'CHARGEDBACK']
  
  - name: dim_payment
    columns:
      - name: payment_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_location
    columns:
      - name: location_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null